### ISSUE TITLE
wiki - music[ ] tag doesn't work in firefox

### ISSUE THREAD

**Issue by HyruleanHero** [wetfish/classic#11]
expected behavior is autoplaying of audio content.
observer behavior is nothing happens.

**Comment by itsrachelfish** [comment]
Fixed! Now you can embed html5 audio onto the wiki using the music[] tag, available options are:
- URL
- Autoplay
- Loop

For example: `music[url|autoplay|loop]`

Supported formats are:
- mp3
- wav
- ogg

Like images, urls outside of wetfish will be automatically rehosted onto the wiki.
