### ISSUE TITLE
wiki - API should provide tag stats

### ISSUE THREAD

**Issue by deepinthebuild** [wetfish/classic#12]
Please add functionality to the wiki API to provide a list of all tags with usage counts.

Additional interesting features would be:
- Query individual tags for all pages tagged with it

**Comment by itsrachelfish** [comment]
There's a new endpoint to list all tags as of f638d7b018f2bd70fc086dd085eabcf54a0d42d5: https://wiki.wetfish.net/api/v1/tags

Querying individual tags would be cool too, but let's make another issue for that
