### ISSUE TITLE
wiki - API requires header info

### ISSUE THREAD

**Issue by deepinthebuild** [wetfish/classic#13]
Making requests to the wetfish API via script fails with 403 Forbidden unless I fake a header.

This works:
`
{'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}
`
but not having to do that or having a default provided would be nice.

**Comment by itsrachelfish** [comment]
The user agent requirement was actually a setting in cloudflare. I updated the cloudflare settings to include an exception for API calls and this is now fixed!
